### ISSUE TITLE
Fallback to Google DNS is not desirable

### ISSUE THREAD

**Issue by keltia** [semihalev/sdns#1]
Please do not fallback on Google resolvers for privacy reasons, more importantly, this can not be overriden in the configuration file like the Root IPs/keys.  I'd use either the local ones or a mix of 1.1.1.1/9.9.9.9/<IPv6 of these> instead.  At the very least, make it a config entry.

**Comment by semihalev** [comment]
This fallback is temporary, we will delete the fallback and will try resolve NS ip addresses better way. Now this configurable.
