### ISSUE TITLE
Feature: Programmic way to change DNS servers sdns is using for lookup

### ISSUE THREAD

**Issue by raguay** [semihalev/sdns#14]
When I turn on my VPN, I would like sdns to use their DNS to lookup external sources. But, all I can find to do it is to have two configs, kill the server, and rerun it with a different config file. I would rather send a command to a TCP/IP port on sdns and change the server address. The sdns program already has an API server. Does that allow for it? Where is documentation for the API server?

**Comment by semihalev** [comment]
It cannot be change via API, but you can bind to 127.0.0.1 and set lookup server this. Your both cases it should be works.
