### ISSUE TITLE
Different zones queries route to different DNS upstream servers

### ISSUE THREAD

**Issue by arvatoth-vcc** [semihalev/sdns#16]
Hi,

Is there any chance to handle different lookups route to different upstrem DNS servers?

For example (meta config structure, not valid):

server {
  label="main_dns";
  ip=8.8.8.8, 8.8.4.4, 1.1.1.1;
  exclude=".office.lan, .private";
}

server {
  label="private_dns";
  ip=192.168.45.1, 10.34.216.1;
  include=".office.lan, .private";
}

Thank you!

**Comment by semihalev** [comment]
Hi,

Currently not supported but [coredns](https://github.com/coredns/coredns) handle your config.

**Comment by arvatoth-vcc** [comment]
Hi,

Thank you for your prompt respose and link!
