### ISSUE TITLE
It doesn't return a glue record when ask NS

### ISSUE THREAD

**Issue by keatonLiu** [semihalev/sdns#189]
Using sdns:
![image](https://github.com/semihalev/sdns/assets/57738324/928f6aa4-7d55-4104-a962-15c6ce7270e9)

Using open resolver (30.30.30.30)
![image](https://github.com/semihalev/sdns/assets/57738324/df82f416-ab22-441a-8ab7-30a482664984)
I want to get the glue record for the name servers, how can I do?

**Comment by semihalev** [comment]
Full resolver servers act not like stub resolver servers. You can check responses from `1.1.1.1` or `8.8.8.8`. Full resolver servers concerns cache memory and cpu usage also there are other concerns for client latency.  You can read the draft additional answers document from https://datatracker.ietf.org/doc/html/draft-fujiwara-dnsop-additional-answers-01
