### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by ookangzheng** [semihalev/sdns#19]
Hi, 
Will you plan this few features in the future?
Like: https://github.com/shawn1m/overture
Feature: 
1. Drop or refuse DNS type: ANY or other
2. Support Dnscrypt v2 protocol?
3. QNAME minimization

Thanks

**Comment by semihalev** [comment]
Hi.

Yes, I already planned these futures.

* ANY type already done,  returning `NOTIMPL` status code
* Dnscrypt is in my TODO list
* QNAME minimization, I'm working on this one, I hope commit soon.

**Comment by semihalev** [comment]
I implemented query minimization. (https://github.com/semihalev/sdns/commit/df9fdedfe150262f84ffc98506527f823367840c) I didn't release yet. I will release soon.

**Comment by semihalev** [comment]
I released v1.0.0 Its included most of new features.
