### ISSUE TITLE
Not loading large blacklist

### ISSUE THREAD

**Issue by PH-68** [semihalev/sdns#193]
It just keep loading large blacklist for a long time with around 10% CPU consumption constantly

![image](https://github.com/semihalev/sdns/assets/58099156/0149943a-3079-4ce4-9379-ac2046ddb90b)

**Comment by semihalev** [comment]
I will test them.

**Comment by semihalev** [comment]
I found double save bug there and fixed on last [commit](https://github.com/semihalev/sdns/commit/92c68237c138de49c6d1ca4554e637cc94126095). (I forget reference link for the issue.) Please clear blacklist directory and try again with last commit.
