### ISSUE TITLE
what problem cause this 

### ISSUE THREAD

**Issue by ookangzheng** [semihalev/sdns#20]
![image](https://user-images.githubusercontent.com/6301735/51434612-187ea500-1c5d-11e9-97cf-90b145fdcbf3.png)
![image](https://user-images.githubusercontent.com/6301735/51434633-68f60280-1c5d-11e9-8f1c-74520b5855ce.png)

I have IPv6 on my server, and using unbound DNS got 100 scores (internet.nl)

**Comment by semihalev** [comment]
Like this testing IPv6 dns servers from resolver. Currently sdns IPv6 supported `client<->server` mode only, `server<->server` IPv6 support is in my todo list. I don't know exactly but if there is only IPv6 DNS servers, sdns cannot reach them currently. Of course sdns should support this for future.
