### ISSUE TITLE
forwarder support for dns over https tls?

### ISSUE THREAD

**Issue by t-e-s-tweb** [semihalev/sdns#200]
currently forwarders are only using port 53 on systems where it might be blocked or privacy is an issue can you add support for doing lookups over dns over https or tls?

alos a basic doh listner without tls so that this app could be used with local porxy like nginx or cloudflared. currently its only tls so it doesn't work if the use case scenario is to used this as a local dns.
also instead of manual whitelist can whitelists be loaded from urls?

**Comment by semihalev** [comment]
Basically, I'm using `sdns` on local without forwarder. It designed as a standalone resolver server but with some advices, I added forwarding option too. Other side. Yes. We can add TLS and HTTPS option too for forwarding. Another side, DoH can be work without TLS too. I'm using nginx as a reverse proxy and behind is working `sdns`. Its cost double TLS. I will check the ideas and I will try my best about this.

Thanks for your advices.
