### ISSUE TITLE
How to open edns?

### ISSUE THREAD

**Issue by FenghenHome** [semihalev/sdns#22]
How to open edns? I am using dig +subnet without answering.

**Comment by FenghenHome** [comment]
root@ubuntu:~# dig @127.0.0.1 -p 53 www.google.com +subnet=1.1.1.1

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.1 -p 53 www.google.com +subnet=1.1.1.1
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 244
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1536
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		300	IN	A	216.58.200.4

;; Query time: 96 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Feb 15 20:35:02 CST 2019
;; MSG SIZE  rcvd: 73

**Comment by semihalev** [comment]
EDNS subnet support currently disabled because of privacy concerns, if you want to use EDNS subnet, you can remove comment on this line https://github.com/semihalev/sdns/blob/master/dnsutil/dnsutil.go#L122 and build again.

**Comment by FenghenHome** [comment]
Hello, guys, thank you for your reply, if I want to use only rootservers to parse dns, what should I do?

**Comment by FenghenHome** [comment]
root@ubuntu:~# dig @127.0.0.1 -p 53 www.google.com +subnet=1.1.1.1

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.1 -p 53 www.google.com +subnet=1.1.1.1
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50713
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1536
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		300	IN	A	216.58.200.4

;; Query time: 20 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Feb 16 10:57:56 CST 2019
;; MSG SIZE  rcvd: 73

**Comment by FenghenHome** [comment]
Has been modified, still can not use edns, please help me!

**Comment by semihalev** [comment]
Your dig version very old, you can update but try like this. 

`dig @127.0.0.1 -p 53 www.google.com +subnet=1.1.1.1 +edns`

**Comment by FenghenHome** [comment]
root@ubuntu:~# dig @127.0.0.1 -p 53 www.google.com +subnet=1.1.1.1 +edns

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.1 -p 53 www.google.com +subnet=1.1.1.1 +edns
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62778
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1536
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		300	IN	A	216.58.200.4

;; Query time: 15 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Feb 16 13:06:04 CST 2019
;; MSG SIZE  rcvd: 73

**Comment by FenghenHome** [comment]
Still can not use edns, please help me!

**Comment by FenghenHome** [comment]
root@ubuntu:~# dig @8.8.8.8 www.google.com +subnet=1.1.1.1 +edns

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @8.8.8.8 www.google.com +subnet=1.1.1.1 +edns
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35828
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
; CLIENT-SUBNET: 1.1.1.1/32/24
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		299	IN	A	172.217.194.103
www.google.com.		299	IN	A	172.217.194.106
www.google.com.		299	IN	A	172.217.194.99
www.google.com.		299	IN	A	172.217.194.104
www.google.com.		299	IN	A	172.217.194.147
www.google.com.		299	IN	A	172.217.194.105

;; Query time: 15 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Feb 16 13:07:10 CST 2019
;; MSG SIZE  rcvd: 151

**Comment by FenghenHome** [comment]
My dig is ok

**Comment by FenghenHome** [comment]
please help me!

**Comment by ben-auo** [comment]
> EDNS subnet support currently disabled because of privacy concerns, if you want to use EDNS subnet, you can remove comment on this line https://github.com/semihalev/sdns/blob/master/dnsutil/dnsutil.go#L122 and build again.

Is this the line to uncomment? https://github.com/semihalev/sdns/blob/master/dnsutil/dnsutil.go#L139
