### ISSUE TITLE
log client ips

### ISSUE THREAD

**Issue by jots** [semihalev/sdns#24]
Is it possible to log client ips that are querying?  I currently have loglevel at debug but don't see them.

**Comment by jots** [comment]
btw, i was interested in this info because when I added my ip to accesslist, i still could not resolve.  found out that  had to add 127.0.0.1 for it to work:
```
accesslist = [
#"0.0.0.0/0",
#"::0/0",
"127.0.0.1/32",
"my_cidr"
]
```
also, it would be great if sdns could log queries that are blocked by blacklists and what blacklist blocked the query.

**Comment by semihalev** [comment]
I will check these.

**Comment by semihalev** [comment]
It can be possible a simple log middleware. Currently, sdns doesn't has log middleware. I will add.

**Comment by semihalev** [comment]
Access log middleware pushed. I will release soon.
