### ISSUE TITLE
[BUG] - errInvalidSignaturePeriod when first create trust-anchor

### ISSUE THREAD

**Issue by keatonLiu** [semihalev/sdns#246]
### Description

![图片](https://github.com/semihalev/sdns/assets/57738324/11737aea-f25b-44b8-bfe6-087f981d3dac)
In function ValidityPeriod(), the rr.Expiration is smaller than utc, so the validation failed.
![图片](https://github.com/semihalev/sdns/assets/57738324/6375dacd-7c89-4dca-bc50-a99c5291b373)
This is the error displayed

### Reproduction steps

```bash
delete db directory, run the application
```

### sdns version

```bash
sdns v1.3.5 rev bb819c1
built by go1.20.6 (windows amd64)
```

### Logs

```bash
INFO[10-28|17:15:39] Starting sdns...                         version=1.3.5
INFO[10-28|17:15:39] Loading config file...                   path=sdns.conf
INFO[10-28|17:15:39] Working directory                        path=db
INFO[10-28|17:15:39] Empty zones loaded                       zones=99
INFO[10-28|17:15:39] DNS server listening...                  net=udp addr=:53
INFO[10-28|17:15:39] DNS server listening...                  net=tcp addr=:53
INFO[10-28|17:15:39] API server listening...                  addr=127.0.0.1:8080
WARN[10-28|17:15:39] No trust anchor state file found or the state corrupted! New one will be generate. path=db\\trust-anchor.db
CRIT[10-28|17:15:39] Root zone keys not verified
```

**Comment by keatonLiu** [comment]
In the last query for the root DNSKEY, the dest server is 2001:500:a8::e
However, it seems that the IPV6 root server returned two expired DNSKEYs
![图片](https://github.com/semihalev/sdns/assets/57738324/9d19bdfb-9274-4324-8e9e-6d2cd7f44993)
![图片](https://github.com/semihalev/sdns/assets/57738324/61153779-ef37-4ccd-b314-5a5ab1ead445)

**Comment by semihalev** [comment]
Checked that. The root server returned expired signed keys. Very interesting. The root server shouldn't return that. In the cache mechanism `sdns` check the RRSIG expire time always. 

Current my query on same IPv6 server:

```shell # dig +multi +dnssec @2001:500:a8::e .

; <<>> DiG 9.10.6 <<>> +multi +dnssec @2001:500:a8::e .
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26662
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
;; QUESTION SECTION:
;.			IN A

;; AUTHORITY SECTION:
.			86400 IN SOA a.root-servers.net. nstld.verisign-grs.com. (
				2023102800 ; serial
				1800       ; refresh (30 minutes)
				900        ; retry (15 minutes)
				604800     ; expire (1 week)
				86400      ; minimum (1 day)
				)
.			86400 IN RRSIG SOA 8 0 86400 (
				20231110050000 20231028040000 46780 .
				D9V/0nf/JaTXjmuQkolhpzx4/bgIb2fGHtFGJhMRuelr
				G/2+gcUTJL5WfTL6R7z++d1ElprgzGNxlsOiGOk96CYO
				hO1VErsGQy+XrnoCZPYVxz8HFD0sNBoZacQTJHTunxTg
				YlT3i3lia29zdLtvFcb2T8uz9MH/lwZ7j6qi5Ig1OhxU
				3HCE+KBQlRMdo4Il27+8B++xTVvCU1d16AQs6WvrnwtN
				dNbBtYk30rqsAHKGpfnpAZQuBupxBat9g2DmJS6BnyXH
				i7nTzSCeSPhXpykw8CnGBWDzKCsrJom35sSYq6KfwKGV
				P+8I5rK/dUeYfn2m4kFSCRuzRREbuVZaeg== )
.			86400 IN NSEC aaa. NS SOA RRSIG NSEC DNSKEY TYPE63
.			86400 IN RRSIG NSEC 8 0 86400 (
				20231110050000 20231028040000 46780 .
				yNnepzODcy24nlwklSOtQ+Xsm0sBtoDEwAfz72ozOwem
				BW+G8tup5QtRnGBxJX4z2ck000jHrIg1dFrh0VUM2MdG
				W5JJ3FRTjN3nrN9HJX+xb9dppd941M6kGPBbEf/xdprl
				WvNBSO+DFd3e35yCubCdnw44tYHI0v/Ay1mDu6mnkc7V
				rnHCGp+DkKDf/VySMApcAKdiZj/IYo1k9rFEtKLoW9Bf
				mYStyvYUH0AeKvk375RyszqwTB7ndgdxxUhtMrwIZuzW
				XtlLOj1o7SUsyBSrIkS5VP7k1MnnyBXLqaHE1QcIq6/J
				pMbuirmdTZ0cXYMiWkGzhlw4VPa0+7571g== )

;; Query time: 23 msec
;; SERVER: 2001:500:a8::e#53(2001:500:a8::e)
;; WHEN: Sat Oct 28 16:18:28 +03 2023
;; MSG SIZE  rcvd: 701```

**Comment by keatonLiu** [comment]
I probably know it. It should be because of the campus network I am using. It may have cached old root server records in the middle. I used mobile data to dig again and the problem was resolved. Can you add a less strict mode so that I can skip the root key verification?

**Comment by semihalev** [comment]
DNSSEC currently sticked on the `sdns`. However, I think we can add dnssec on/off in the configuration.

**Comment by keatonLiu** [comment]
Ok, that should be useful in some cases

**Comment by semihalev** [comment]
I added the future on dnssec-1 branch. You can test it.

**Comment by keatonLiu** [comment]
I will test it. Thank you,

**Comment by keatonLiu** [comment]
After setting dns="off", another interesting error occurred, which says A record count mismatch. 
It because my campus network does not return a glue rr for the root NSs. 
This is the wireshark capture:
![image](https://github.com/semihalev/sdns/assets/57738324/656d76cb-0682-486f-9e0e-3a071e220502)
This is the debug: 
![image](https://github.com/semihalev/sdns/assets/57738324/cbfaa153-be7d-47a9-8f5d-3895a1bb9e3c)

**Comment by keatonLiu** [comment]
After setting dns="off", another interesting error occurred, which says A record count mismatch. 
It because my campus network does not return a glue rr for the root NSs. 
This is the wireshark capture:
![image](https://github.com/semihalev/sdns/assets/57738324/656d76cb-0682-486f-9e0e-3a071e220502)
This is the debug: 
![image](https://github.com/semihalev/sdns/assets/57738324/cbfaa153-be7d-47a9-8f5d-3895a1bb9e3c)

**Comment by keatonLiu** [comment]
I tested it and found that it might be the dnsmasq server of the router in my dormitory. After shutting it down, I can check the glue records. I'm trying to figure this out

**Comment by keatonLiu** [comment]
I finally understand. The dnsmasq on my router takes over all requests towards port 53, so all requests are redirected to the upstream server configured in dnsmasq. 
Therefore when I type:
```shell
dig  . NS @192.58.128.30
```
The DNS request won't be passed to 192.58.128.30 but intercepted by dnsmasq and send to the upstream server. Because glue records will only be returned by authoritative servers. So there wont be a glue record in the response.
