### ISSUE TITLE
panic: root zone DS not verified

### ISSUE THREAD

**Issue by lygstate** [semihalev/sdns#25]
t=2019-04-10T10:01:06+0000 lvl=info msg="Starting sdns..." version=0.2.2-rc1
panic: root zone DS not verified

goroutine 1 [running]:
main.(*Resolver).verifyRootKeys(0xc000264990, 0xc000272090, 0x1)
        /go/src/github.com/semihalev/sdns/resolver.go:705 +0x3c5
main.(*Resolver).verifyDNSSEC(0xc000264990, 0xbdbbcc, 0x3, 0x114706e, 0x1, 0x114706e, 0x1, 0xc000272090, 0xc000204440, 0x2, ...)
        /go/src/github.com/semihalev/sdns/resolver.go:744 +0x9a5
main.(*Resolver).Resolve(0xc000264990, 0xbdbbcc, 0x3, 0xc000214d80, 0xc00007e6c0, 0xcb5001, 0x1e, 0x0, 0xc00027e000, 0x0, ...)
        /go/src/github.com/semihalev/sdns/resolver.go:171 +0x65f
main.(*Resolver).verifyDNSSEC(0xc000264990, 0xbdbbcc, 0x3, 0x114706e, 0x1, 0xbdb4f4, 0x1, 0xc000272000, 0xc0002042e0, 0x2, ...)
        /go/src/github.com/semihalev/sdns/resolver.go:728 +0xb19
main.(*Resolver).Resolve(0xc000264990, 0xbdbbcc, 0x3, 0xc000215ac8, 0xc00007e6c0, 0xc000245001, 0x5, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/semihalev/sdns/resolver.go:171 +0x65f
main.(*Resolver).checkPriming(0xc000264990, 0xc000082840, 0xc0000c6400)
        /go/src/github.com/semihalev/sdns/resolver.go:833 +0x1c9
main.NewResolver(0x10)
        /go/src/github.com/semihalev/sdns/resolver.go:55 +0x124
main.NewHandler(0x4)
        /go/src/github.com/semihalev/sdns/handler.go:33 +0x22
main.(*Server).Run(0xc0000827e0)
        /go/src/github.com/semihalev/sdns/server.go:31 +0x37
main.start()
        /go/src/github.com/semihalev/sdns/main.go:171 +0x2e3
main.main()
        /go/src/github.com/semihalev/sdns/main.go:184 +0xb7

**Comment by semihalev** [comment]
I updated root DS in config, you can use latest commit.
