### ISSUE TITLE
[BUG] - Test_ClientTimeout failed 

### ISSUE THREAD

**Issue by Dexus** [semihalev/sdns#279]
### Description

=== RUN   Test_ClientTimeout
    client_test.go:29:
                Error Trace:    /root/sdns/middleware/resolver/client_test.go:29
                Error:          An error is expected but got nil.
                Test:           Test_ClientTimeout
--- FAIL: Test_ClientTimeout (0.01s)

### Reproduction steps

```bash
build from source and use makefile:

make

on tests it failing
```

### sdns version

```bash
current source
```

### OS

Linux

**Comment by semihalev** [comment]
Thanks for your report. This is fixed in v1.3.7
