### ISSUE TITLE
[BUG] - build example plugin not possible

### ISSUE THREAD

**Issue by Dexus** [semihalev/sdns#280]
### Description

It is not possible to build the example plugin, so it would work.
If I checkout both repos, and try to build it as the readme told me, I cant load the plugin.

Once I build the `sdns` with `CGO_ENABLED=1` I can load the plugin, but not it will not accept the function assert in line 111 in middelware.go (`newFn, ok := newFuncSym.(func(cfg *config.Config) Handler)`)

### Reproduction steps

```bash
# this is from github release
Apr 09 13:04:40 homeprinter sdns[3382185]: t=2024-04-09T13:04:40+0200 lvl=eror msg="Plugin open failed" plugin=wildcardhostsfile error="plugin: not implemented" 

or

# this is selfbuild from source with CGO_ENABLED=1
Apr 09 13:25:22 homeprinter sdns[3399475]: t=2024-04-09T13:25:22+0200 lvl=eror msg="Plugin new function assert failed" plugin=wildcardhostsfile
```

### sdns version

```bash
1.3.6 from releases (without CGO_ENABLED=1)
also 1.3.6 self build with CGO_ENDABLED=1
```

### OS

Linux

**Comment by semihalev** [comment]
I updated dependencies for [sdnexampleplugin](https://github.com/semihalev/sdnsexampleplugin). This may help about that. I tested for this example working well.

**Comment by Dexus** [comment]
Okay, now it works, but I had to update all repos with `go get -u` because it told me

```
Apr 09 16:45:38 homeprinter sdns[3469589]: t=2024-04-09T16:45:38+0200 lvl=eror msg="Plugin open failed" plugin=exampleplugin error="plugin.Open(\"/root/git/sdnsexampleplugin/exampleplugin\"): plugin was built with a different version of package golang.org/x/sys/unix"
```

So it is a must to build both sdns and plugins at the sametime, because else once a package is a indirect dep, it can't work...

**Comment by Dexus** [comment]
And a additional note: Found my fail from the `Apr 09 13:25:22 homeprinter sdns[3399475]: t=2024-04-09T13:25:22+0200 lvl=eror msg="Plugin new function assert failed" plugin=wildcardhostsfile` error, that was because I copied a bit from the hostsfile middleware and did not change it to the middleware.Handler as output.
