### ISSUE TITLE
code review: question/comment

### ISSUE THREAD

**Issue by miekg** [semihalev/sdns#3]
I'm opening issue as I go through your code (hope you don't mind).

In resolver. go the rootserver and root6server are both hardcoded. Usually these things live in a root.hints file. I.e. would be good to factor that out.

Further more there is a thing called priming; i.e. you go to the root and you validate (and update) the hints file with the data you get from (some) root servers. Is something like this currently implemented?

**Comment by miekg** [comment]
ah, there is also configuration in sdns.toml

**Comment by semihalev** [comment]
Always welcome here.

I hardcoded the default servers in resolver.go but They can be override via config file (config.go)

I read the RFC 8109 now. I didn't know the RFC, thanks.  I added to todo list now.  The priming query is very simple implementation.

**Comment by semihalev** [comment]
f98e2e38ff3f275350aa3b3ee8d5ae682dc33321

I just implemented RFC 8109. Thanks for the trick.
