### ISSUE TITLE
HTTP API usage

### ISSUE THREAD

**Issue by trewqqwert** [semihalev/sdns#60]
I'm experimenting with the HTTP API and all requests get 404 errors. 

Here is an example I found in test cases. 
`GET http://127.0.0.1:8080/dns-query?name=www.google.com&type=a&do=true&cd=true&edns_client_subnet=127.0.0.1/32`

Is there any user guide on HTTP API?

**Comment by semihalev** [comment]
HTTP API and DoH is different sockets. If you want to use DoH you should open this from _sdns.conf_

```
# Address to bind to for the DNS-over-HTTPS server
# binddoh = ":8053"
```

Also DoH need TLS certificate and private key. You can set this from _sdns.conf_

```
# TLS certificate file
# tlscertificate = "server.crt"

# TLS private key file
# tlsprivatekey = "server.key"
```

You can find the [HTTP API](https://github.com/semihalev/sdns/blob/master/api/README.md) docs here.

**Comment by trewqqwert** [comment]
I see. Mistook the HTTP API for DoH. 

Thanks for your update.
