### ISSUE TITLE
Request to add forwarding dns function

### ISSUE THREAD

**Issue by thb007** [semihalev/sdns#64]
Currently the sdns program does not support the forwarding of dns query functions. For example, I can forward all dns domain name queries to 1.1.1.1 and 8.8.8.8 for resolution.

**Comment by semihalev** [comment]
I will add forwarder middleware in v1.2.0.

**Comment by thb007** [comment]
> I will add forwarder middleware in v1.2.0.

Thank you,

**Comment by semihalev** [comment]
I implemented forwarder middleware. I didn't release yet. I will release soon. You can test from latest source.

**Comment by thb007** [comment]
> I implemented forwarder middleware. I didn't release yet. I will release soon. You can test from latest source.

ok.But edns does not support the client subnet IP

**Comment by matti** [comment]
`forwarderservers` is mentioned in the README.md but missing from the generated conf?

**Comment by semihalev** [comment]
I just released v1.2.1. This version added the forwarder.
