### ISSUE TITLE
RFC 5011 support

### ISSUE THREAD

**Issue by miekg** [semihalev/sdns#7]
RFC 5011:  Automated Updates of DNS Security (DNSSEC) Trust Anchors

is an RFC that tells you how to detect a root (KSK) key rollover happens and how to update your currently configured root-anchor.

I haven't implemented this myself, but it would be a nice addition.

**Comment by semihalev** [comment]
I read the RFC before and exactly it's very useful and necessary here. I will check technical details again in RFC about this.

**Comment by semihalev** [comment]
Hey Miek,

I added the auto trust anchors support on last commit. I read on [ICANN](https://www.icann.org/en/announcements/details/icann-announces-schedule-to-generate-new-keys-for-ksk-key-rollover-02-03-2023-en), new KSK rollover soon. I made test server for root zone for all rollover states. This update successfully update trust anchors as described 5011 on my tests. 

Thanks for your support.
