### ISSUE TITLE
parallel queries

### ISSUE THREAD

**Issue by miekg** [semihalev/sdns#8]
The resolver does parallel lookup:
~~~
	// Start lookup on each nameserver top-down, in interval
	for index, server := range servers {
		go L(server, len(servers)-1 == index)
 ....
~~~
This is nice for latency, but it breaks things at larger scales. For one you get an awful lot of queries which means you can get blocked (common in cloud providers).
The config.Interval mitigates against this which is good - how did you determine that interval?

**Comment by semihalev** [comment]
default 200ms, it can be change from config but most of cases auth servers response time average is 100ms (depends network latency), if you have any information about this, I will be happy.

We can set hardcoded minimal interval, user-typed lower intervals may harm auth servers.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [semihalev/sdns] parallel queri..." ]
>default 200ms, it can be change from config but most of cases auth servers response time average is 100ms (depends network latency), if you have any information about this, I will be happy.
>
>We can set hardcoded minimal interval, user-typed lower intervals may harm auth servers.

I don't think a user should care about this setting, but in cases the DNS 
latency creeps up you will be sending more queries, potentially making a bad 
situation worse.

Do you an idea how many queries you are sending on average to upstream 
nameservers?

**Comment by semihalev** [comment]
Parallel queries removed, just using minimal read timeout, looks better.
